name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [12, 14, 15]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: |
        npm ci
    - name: Build
      run: npm run build
    
    - name: Check un-tracked changes in /dist using git porcelain command
      run: |
        if [[ `git status ./dist --porcelain` ]]
        then
          echo "ERROR: running the previous command has introduced changes. Hence, Failing the build."
          git status --porcelain
          exit 1
        fi
    
    - name: Lint
      run: npm run lint

    - name: Test w/ Coverage
      run: npm test -- --coverage
